In [1]:
import numpy as np

In [3]:
x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [4]:
# ndarray from tuple
x=(1,2,3)'
a=np.asarray(x)
print(a)

SyntaxError: unterminated string literal (detected at line 2) (1815479447.py, line 2)

In [5]:
# create matrix  in numpy
# in numpy, we use the np.array() function to create a matrix. for example,

In [10]:
matrix1=np.array([[1,3],[5,7]])
print("2x2 matrix:\n",matrix1)

2x2 matrix:
 [[1 3]
 [5 7]]


In [1]:
# perform matrix multiplication in numpy
# we use the np.dot() function to perform multiplication between two matrices 
# the number of columns of first matrix and the number of rows of second matrix then multiplication is possible

In [2]:
import numpy as np

In [3]:
# create two matrices 

In [6]:
matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])
result=np.dot(matrix1,matrix2)
print("matrix1 x matrix2:\n",result)

matrix1 x matrix2:
 [[14 30]
 [38 86]]


In [8]:
# CREATE A MATRIX
matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()

[[1 3]
 [5 7]]



In [9]:
# get transpose of matrix1 ( for conversion of rows to column)
result=np.transpose(matrix1)
print(result)

[[1 5]
 [3 7]]


In [10]:
# numpy.hstack function---horizantally stack numpy arrays using numpy.hstack()
import numpy as np
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
print(np.hstack((x,y)))

[3 5 7]

[5 7 9]

[3 5 7 5 7 9]


In [11]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.hstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3 5]
 [5 7]
 [7 9]]


In [12]:
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
print(np.vstack((x,y)))

[3 5 7]

[5 7 9]

[[3 5 7]
 [5 7 9]]


In [13]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.vstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3]
 [5]
 [7]
 [5]
 [7]
 [9]]


# numpy.arrange
this function returns an ndarray object containing evenly spaced values within a given range

In [15]:
#  an array of evenly spaced numbers
import numpy as np
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
# this is dimensional array
import numpy as np
a=np.arange(24)
a.ndim

1

In [19]:
import numpy as np
a=np.arange(5,dtype=float)
print(x)

[[3]
 [5]
 [7]]


In [20]:
# start and stop parameters set
import numpy as np
x=np.arrange(10,20,2)
print(a)

AttributeError: module 'numpy' has no attribute 'arrange'